import configparser
import os

def read_config():
	config = configparser.ConfigParser()
	config.read(f'{os.path.dirname(__file__)}/../config.ini')
	return config

def get_random_key(seed: int=32) -> bytes:
	"""
	Return random key generated by Crypto.Random
	"""
	from Crypto.Random import get_random_bytes
	key = get_random_bytes(seed)
	return key


def get_golden_key_dict(pwd: str, key_length: int=32) -> dict:
	"""
	Generate golden key
	"""
	from Crypto.Protocol.KDF import PBKDF2
	salt = get_random_key()
	key = PBKDF2(pwd, salt, dkLen=key_length)
	return {pwd: (salt, key)}
